

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "LIKE ZERO TEST",
    "author": "Max Ver",
    "url": "http://bbc.com"
}

//GET http://localhost:3003/api/blogs

//DELETE http://localhost:3003/api/blogs/5f45f19d06959310ad7ad252
